/**
 * Core type definitions for the internal music library database.
 * Based on the structure generated by indexation.bat.
 */

import { RepeatMode } from './playback';

export interface LibraryOwnerInfo {
    first_name: string;
    last_name: string;
    nickname: string;
    full_name: string;
}

export interface LibraryInfo {
    owner: LibraryOwnerInfo;
    date: string;
    total_tracks_versions: number;
    execution_time_ms: number;
}

export interface TrackHierarchy {
    group: string;
    album: string | null;
    folder: string | null;
}

export interface TrackLogic {
    hash_sha256: string;
    track_name: string;
    version_name: string;
    total_versions_in_folder: number;
    is_single: boolean;
    hierarchy: TrackHierarchy;
}

export interface TrackFile {
    name: string;
    ext: string;
    path: string;
    dir: string;
    size_bytes: number;
    size_mb: number;
    created: string;
    modified: string;
    epoch_created: number;
    epoch_modified: number;
}

export interface TrackMetadata {
    title: string;
    artists: string[];
    album_artist: string;
    composer: string;
    album: string;
    genre: string | null;
    year: string | null;
    track_number: string | null;
    total_tracks: string | null;
    disc_number: string | null;
    total_discs: string | null;
    bpm: string | null;
    lyrics: string | null;
    comment: string | null;
    description: string | null;
    // Expanded fields
    producer: string | null;
    label: string | null;
    publisher: string | null;
    isrc: string | null;
    upc: string | null;
    mood: string | null;
    language: string | null;
    category: string | null;
    tags: string[] | null;
    remix_artist: string | null;
    edition: string | null;
    recording_year: string | null;
    video_link: string | null;
    streaming_link: string | null;
}

export interface AudioSpecs {
    is_lossless: boolean;
    duration: string | null;
    codec: string | null;
    bitrate: string | null;
    sample_rate: string | null;
    channels: string | null;
}

export interface ImageDetails {
    name: string;
    type: string;
    path: string;
    size_bytes: number;
    dimensions: string;
    aspect_ratio: 'Square' | 'Landscape' | 'Portrait' | 'Unknown';
    dominant_color: string;
    average_color?: string;
    vibrant_color?: string;
    muted_color?: string;
    dark_color?: string;
    light_color?: string;
    accent_color?: string;
    color_palette?: Array<{
        hex: string;
        rgb?: { r: number; g: number; b: number };
        hsl?: { h: number; s: number; l: number };
        coverage_percent?: number;
        role?: string;
    }>;
}

export interface TrackArtworks {
    track_artwork: ImageDetails[];
    album_artwork: ImageDetails[];
}

export interface TrackItem {
    id: number;
    logic: TrackLogic;
    file: TrackFile;
    metadata: TrackMetadata;
    audio_specs: AudioSpecs;
    artworks: TrackArtworks;
    versions?: TrackItem[];
}

export interface MusicDatabase {
    info: LibraryInfo;
    items: TrackItem[];
}

export interface AlbumGroup {
    name: string;
    artist: string;
    tracks: TrackItem[];
    artworkDetails?: ImageDetails;
    artworkPath?: string;
    dominantColor: string;
}

// Application State Interfaces
export interface PlayerState {
    currentTrack: TrackItem | null;
    isPlaying: boolean;
    volume: number;
    queue: TrackItem[];
    history: TrackItem[];
    shuffle: boolean;
    shuffleMode: import('../services/persistence').ShuffleMode;
    repeat: RepeatMode;
    autoplay: boolean;
    queueLimit: number;
}

export interface QueueDisplayItem {
    originalIndex: number;
    id: string;
    startTimeSeconds: number;
    logic: TrackLogic;
    metadata: TrackMetadata;
    audio_specs: AudioSpecs;
    artworks: TrackArtworks;
    versions?: TrackItem[];
}

export interface ColumnConfig {
    id: string;
    label: string;
    width: number;
    visible: boolean;
    sortable: boolean;
}

export interface LibraryState {
    tracks: TrackItem[];
    filteredTracks: TrackItem[];
    isLoading: boolean;
    searchQuery: string;
    sortBy: string;
    sortOrder: 'asc' | 'desc';
    filterBy: Record<string, any>;
    columnConfig: ColumnConfig[];
    versionToPrimaryMap: Record<string, string>;
    stats: {
        totalDuration: number;
        totalTracks: number;
        totalSizeMb: number;
    };
}

